#:schema https://mise.jdx.dev/schema/mise.json

[settings]
dotfiles.root = "~/.dotfiles"

[tools]
# Git tools
gh = "latest"
lazygit = "latest"
hk = "latest"
delta = "latest"

# Language servers
tombi = "latest"
pkl = "latest"

[dotfiles]
"~/.config/mise/config.toml" = "~/.dotfiles/mise.toml"
